config/routes.rb
Rails.application.routes.draw do
  root to: "users#new"

  resources :users, only: [:new, :create, :show]
  resource :session, only: [:new, :create, :destroy]
  resources :goals, except: [:index]

end

app/models/goal.rb
# == Schema Information
#
# Table name: goals
#
#  id         :integer          not null, primary key
#  title      :string           not null
#  body       :text             not null
#  user_id    :integer          not null
#  public     :string           default("t"), not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Goal < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :integer          not null, primary key
#  username        :string           not null
#  password_digest :string           not null
#  session_token   :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#

class User < ActiveRecord::Base
  after_initialize :ensure_token
  attr_reader :password
  validates :username, :password_digest, :session_token, presence: true
  validates :password, length: {minimum: 6, allow_nil:true }
  has_many :goals

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    return nil if user.nil?
    user.is_password?(password) ? user : nil
  end

  def password=(password)
    @password=password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def reset_token
    self.session_token = SecureRandom.urlsafe_base64
    self.save
    self.session_token
  end

  def ensure_token
    self.session_token ||= SecureRandom.urlsafe_base64
  end


end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find_by_session_token(session[:session_token])
  end

  def logged_in?
    !!current_user
  end

  def login(user)
    session[:session_token] = user.reset_token
    @current_user = user
  end

  def logout
    current_user.reset_token
    session[:session_token] = nil
  end

  private

  def user_params
    params.require(:user).permit(:username, :password)
  end
end

app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  def new
    @goal = Goal.new
  end

  def create
    @goal = Goal.new(goal_params)
    @goal.user_id = current_user.id
    if @goal.save
      redirect_to user_url(@goal.user)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def edit
    @goal = Goal.find(params[:id])
  end

  def update
    @goal = Goal.find(params[:id])
    if @goal
      @goal.update(goal_params)
      redirect_to @goal
    else
      flash.now[:errors] = ["Goal not found"]
      render :edit
    end
  end

  def destroy
    @goal = Goal.find(params[:id])
    @goal.destroy
    redirect_to user_url(@goal.user)
  end

  def show
    @goal = Goal.find(params[:id])
  end

  private

  def goal_params
    params.require(:goal).permit(:title, :body, :public, :status)
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  # before_action :ensure_signed_out

  def new
    @user = User.new
  end

  def create

    @user = User.find_by_credentials(user_params[:username], user_params[:password])
    if @user
      login(@user)
      redirect_to @user
    else
      @user = User.new
      flash.now[:errors] = ["Invalid username or password"]
      render :new
    end
  end

  def destroy
    logout
    redirect_to new_session_url
  end

  private

  # def ensure_signed_out
  #   redirect_to user_url(current_user) if logged_in?
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      login(@user)
      redirect_to @user
    else
      flash.now[:errors] = @user.errors.full_messages
      render :new
    end
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def auth_token
    "<input type='hidden' name='authenticity_token' value='#{ form_authenticity_token }'>".html_safe
  end
end

app/helpers/goals_helper.rb
module GoalsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/goals/_form.html.erb
<% title = goal.persisted? ? "Update Goal" : "Save" %>
<% action = goal.persisted? ? goal_url(goal) : goals_url %>
<% html_verb = goal.persisted? ? "PUT" : "POST" %>

<h1><%= title %></h1>
<form action = "<%= action %>" method = "Post">
<input type ="hidden" name="_method" value="<%=html_verb%>">
<%= auth_token %>

<label>Title
<input type="text" name="goal[title]" value="<%=goal.title%>">
</label><br>

<label>Body
<textarea name="goal[body]"><%=goal.body%></textarea>
</label><br><br>

<label>Public
  <br>
  <label>Yes
  <input type="radio" name="goal[public]" value="Yes" checked>
</label><br>
  <label>No
  <input type="radio" name="goal[public]" value="No" >
  </label>
</label><br><br>

<label>Status</label><br>
  <input type="radio" name="goal[status]" value="incomplete">Incomplete<br>
  <input type="radio" name="goal[status]" value="complete">Complete<br><br>

<input type="submit" value="Save">

app/views/goals/edit.html.erb
<%= render "form", goal: @goal %>

app/views/goals/new.html.erb
<%= render "form", goal: @goal %>

app/views/goals/show.html.erb
goals#show <br><br>

Title: <%= @goal.title %><br>
Body: <%= @goal.body %><br>
Status : <%= @goal.status %><br><br>


<%= link_to "Edit", edit_goal_url(@goal) %><br>
<%= link_to "Delete", goal_url(@goal), method: :delete %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GoalApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <ul>
      <li><%= error %></li>
    </ul>
  <% end %>
<% end %>

<% if logged_in? %>
<%= current_user.username %>
<%= button_to "Sign Out", session_url, method: :delete %>
<% else %>
<%= link_to "Sign In", new_session_url %>
<%= link_to "Sign Up", new_user_url %>
<% end %>
<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<form action="<%= users_url %>" method="post">
<%= auth_token %>

<label>
  User Name
  <input type="text" name="user[username]" value="<%= @user.username %>">
</label><br>

<label>
  Password
  <input type="password" name="user[password]">
</label><br>

<input type="submit" value="Sign Up">
</form>

app/views/users/show.html.erb
users#show

<% if logged_in? %>
<h1><%= @user.username %>'s goals</h1>

<% Goal.all.each do |goal| %>
<ul>
  <% if goal.public == "Yes" || goal.user_id == current_user.id %>
<li><%= link_to goal.title, goal_url(goal)%> <%= "Author: #{goal.user.username}" %></li>
<li>Status: <%= goal.status  %></li>
<li>Public: <%= goal.public %></li>
    <% end %>
</ul>
<% end %>

<%= button_to "New Goal", new_goal_url, method: :get %>
<% end %>